-- MySQL Script generated by MySQL Workbench
-- lun 11 sep 2017 23:33:17 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cuatro_enfoques
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuatro_enfoques
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuatro_enfoques` ;
USE `cuatro_enfoques` ;

-- -----------------------------------------------------
-- Table `cuatro_enfoques`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuatro_enfoques`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profession` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuatro_enfoques`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuatro_enfoques`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_projects_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `cuatro_enfoques`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuatro_enfoques`.`stakeholders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuatro_enfoques`.`stakeholders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `decription` TEXT NOT NULL,
  `function` VARCHAR(45) NOT NULL,
  `profession` VARCHAR(45) NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stakeholders_projects1_idx` (`projects_id` ASC),
  CONSTRAINT `fk_stakeholders_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `cuatro_enfoques`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuatro_enfoques`.`goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuatro_enfoques`.`goals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `relevance` VARCHAR(45) NOT NULL,
  `stakeholders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goals_stakeholders1_idx` (`stakeholders_id` ASC),
  CONSTRAINT `fk_goals_stakeholders1`
    FOREIGN KEY (`stakeholders_id`)
    REFERENCES `cuatro_enfoques`.`stakeholders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuatro_enfoques`.`softgoals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuatro_enfoques`.`softgoals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `relevance` VARCHAR(45) NOT NULL,
  `goals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_softgoals_goals1_idx` (`goals_id` ASC),
  CONSTRAINT `fk_softgoals_goals1`
    FOREIGN KEY (`goals_id`)
    REFERENCES `cuatro_enfoques`.`goals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuatro_enfoques`.`nfrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuatro_enfoques`.`nfrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuatro_enfoques`.`softgoals_has_nfrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuatro_enfoques`.`softgoals_has_nfrs` (
  `softgoals_id` INT NOT NULL,
  `nfrs_id` INT NOT NULL,
  PRIMARY KEY (`softgoals_id`, `nfrs_id`),
  INDEX `fk_softgoals_has_nfrs_nfrs1_idx` (`nfrs_id` ASC),
  INDEX `fk_softgoals_has_nfrs_softgoals1_idx` (`softgoals_id` ASC),
  CONSTRAINT `fk_softgoals_has_nfrs_softgoals1`
    FOREIGN KEY (`softgoals_id`)
    REFERENCES `cuatro_enfoques`.`softgoals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_softgoals_has_nfrs_nfrs1`
    FOREIGN KEY (`nfrs_id`)
    REFERENCES `cuatro_enfoques`.`nfrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
